/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SdkTestRouteImport } from './routes/sdk-test'
import { Route as SdkPublishedTestRouteImport } from './routes/sdk-published-test'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SdkTestRoute = SdkTestRouteImport.update({
  id: '/sdk-test',
  path: '/sdk-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkPublishedTestRoute = SdkPublishedTestRouteImport.update({
  id: '/sdk-published-test',
  path: '/sdk-published-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sdk-published-test': typeof SdkPublishedTestRoute
  '/sdk-test': typeof SdkTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sdk-published-test': typeof SdkPublishedTestRoute
  '/sdk-test': typeof SdkTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sdk-published-test': typeof SdkPublishedTestRoute
  '/sdk-test': typeof SdkTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/sdk-published-test' | '/sdk-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/sdk-published-test' | '/sdk-test'
  id: '__root__' | '/' | '/dashboard' | '/sdk-published-test' | '/sdk-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SdkPublishedTestRoute: typeof SdkPublishedTestRoute
  SdkTestRoute: typeof SdkTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sdk-test': {
      id: '/sdk-test'
      path: '/sdk-test'
      fullPath: '/sdk-test'
      preLoaderRoute: typeof SdkTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk-published-test': {
      id: '/sdk-published-test'
      path: '/sdk-published-test'
      fullPath: '/sdk-published-test'
      preLoaderRoute: typeof SdkPublishedTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SdkPublishedTestRoute: SdkPublishedTestRoute,
  SdkTestRoute: SdkTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
