import { createFileRoute } from "@tanstack/react-router";
import {
  CodeBlock,
  PageTitle,
  SectionHead,
  RefTable,
  RefTableHead,
  RefRow,
} from "@/components/docs/primitives";

export const Route = createFileRoute("/docs/types")({
  component: TypesPage,
});

const SNIPPET_ENVELOPE = `interface TranslationEnvelope {
  id: string;              // unique translation ID
  inputText: string;       // original text the user submitted
  normalizedText: string;  // cleaned / lowercased version
  plan: SignPlan;          // the full animation plan
  createdAt: number;       // unix timestamp (ms)
}`;

const SNIPPET_SIGN_PLAN = `interface SignPlan {
  glossText: string;     // space-separated ASL gloss (e.g. "HELLO YOU HOW")
  frames: FrameItem[];   // ordered animation primitives
  durationMs: number;    // total estimated playback duration
}`;

const SNIPPET_FRAME_ITEM = `// FrameItem is a discriminated union — three variants:

// 1. Named pose from the lexeme pose library
interface PoseFrame {
  type: "pose";
  id: string;                           // pose library key
  durationMs: number;
  blend: "blend" | "snap" | "none";    // transition to this pose
}

// 2. Rest / pause between signs
interface PauseFrame {
  type: "pause";
  durationMs: number;
}

// 3. Fingerspell sequence (expands into individual letter poses)
interface SpellFrame {
  type: "spell";
  letters: string[];    // e.g. ["H", "E", "L", "L", "O"]
  durationMs: number;
}`;

const SNIPPET_SIGN_TOKEN = `// SignToken — the discriminated union of all gloss token types:

{ type: "lexeme";  id: string }           // named sign from the lexicon
{ type: "spell";   letters: string[] }    // fingerspelled word
{ type: "pause";   durationMs: number }   // deliberate rest
{ type: "unknown"; raw: string }          // unrecognized gloss token`;

const SNIPPET_FEATURE_VECTOR = `// 14-field vector produced by FeatureExtractor for each frame
interface FeatureVector {
  fingerprint: number;          // compact hash of finger extension states
  thumbVsFingerDepth: number;   // relative depth difference (thumb vs. fingers)
  spatialZone: number;          // quantized hand position zone (1–9 grid)
  palmNormal: [number, number, number];  // normalized palm orientation
  wristAngle: number;           // wrist rotation in radians
  // … 9 additional geometry fields
}`;

const SNIPPET_RUNTIME_SNAPSHOT = `interface RuntimeSnapshot {
  status: "idle" | "recording" | "translating" | string;
  isTranslating: boolean;
  lastEnvelope: TranslationEnvelope | null;
  compositionTokens: CompositionToken[];
  compositionText: string;
  speechStatus: "idle" | "capturing" | "processing";
  speechLevel: number;  // 0–1
  error: string | null;
}`;

const SNIPPET_IMPORTS = `// All types are available from:
import type { TranslationEnvelope, SignPlan, FrameItem } from "@ikiraro/engine/types";
import type { RuntimeSnapshot } from "@ikiraro/runtime";

// Or transitively via the SDK entry point:
import type { TranslationEnvelope } from "@ikiraro/sdk";`;

function TypesPage() {
  return (
    <div className="space-y-12">
      <PageTitle
        title="Key Types"
        subtitle="All types are exported from @ikiraro/engine/types and @ikiraro/runtime. They're also available transitively from the SDK entry point."
      />

      {/* Imports */}
      <section className="space-y-4">
        <SectionHead id="imports" label="Importing types" />
        <CodeBlock code={SNIPPET_IMPORTS} label="type imports" />
      </section>

      {/* TranslationEnvelope */}
      <section className="space-y-4">
        <SectionHead id="translation-envelope" label="TranslationEnvelope" />
        <p className="text-muted-foreground text-[13px] leading-relaxed">
          The top-level output of every translation. Returned by{" "}
          <code className="font-mono text-foreground">onTranslated</code>, stored in{" "}
          <code className="font-mono text-foreground">snapshot.lastEnvelope</code>, and passed to{" "}
          <code className="font-mono text-foreground">AvatarViewer</code>.
        </p>
        <CodeBlock code={SNIPPET_ENVELOPE} label="TranslationEnvelope" />
        <RefTable>
          <RefTableHead cols={["Field", "Type", "Description"]} />
          <RefRow
            name="id"
            type="string"
            desc="Unique ID per translation run — safe to use as a React key."
          />
          <RefRow name="inputText" type="string" desc="Raw text submitted by the user." />
          <RefRow
            name="normalizedText"
            type="string"
            desc="Cleaned version — lowercased, punctuation removed."
          />
          <RefRow
            name="plan"
            type="SignPlan"
            desc="The full animation plan generated by the planner."
          />
          <RefRow
            name="createdAt"
            type="number"
            desc="Unix timestamp (ms) when the translation completed."
          />
        </RefTable>
      </section>

      {/* SignPlan */}
      <section className="space-y-4">
        <SectionHead id="sign-plan" label="SignPlan" />
        <p className="text-muted-foreground text-[13px] leading-relaxed">
          The intermediate representation between the planner and the renderer. Both{" "}
          <code className="font-mono text-foreground">DeterministicUnitsPlanner</code> (no LLM) and{" "}
          <code className="font-mono text-foreground">GroqSemanticPlanner</code> produce a SignPlan.
          The RendererDirector consumes <code className="font-mono text-foreground">frames</code>{" "}
          one by one.
        </p>
        <CodeBlock code={SNIPPET_SIGN_PLAN} label="SignPlan" />
      </section>

      {/* FrameItem */}
      <section className="space-y-4">
        <SectionHead id="frame-item" label="FrameItem" />
        <p className="text-muted-foreground text-[13px] leading-relaxed">
          A discriminated union of animation primitives. The RendererDirector drains the{" "}
          <code className="font-mono text-foreground">frames</code> queue frame by frame, applying
          the blend mode when transitioning between poses.
        </p>
        <CodeBlock code={SNIPPET_FRAME_ITEM} label="FrameItem" />
        <RefTable>
          <RefTableHead cols={["Blend mode", "Description"]} />
          <RefRow
            name="blend"
            desc="Smooth interpolation between the previous pose and this one. Used for natural lexeme transitions. Default for most signs."
          />
          <RefRow
            name="snap"
            desc="Immediate cut — no transition. Used between fingerspelled letters to avoid blurring."
          />
          <RefRow
            name="none"
            desc="Hold the previous pose and then cut. Used for deliberate holds."
          />
        </RefTable>
      </section>

      {/* SignToken */}
      <section className="space-y-4">
        <SectionHead id="sign-token" label="SignToken" />
        <p className="text-muted-foreground text-[13px] leading-relaxed">
          Gloss tokens produced by the LLM and classified by the planner before being expanded into{" "}
          <code className="font-mono text-foreground">FrameItem</code>s.
        </p>
        <CodeBlock code={SNIPPET_SIGN_TOKEN} label="SignToken variants" />
      </section>

      {/* RuntimeSnapshot */}
      <section className="space-y-4">
        <SectionHead id="runtime-snapshot" label="RuntimeSnapshot" />
        <p className="text-muted-foreground text-[13px] leading-relaxed">
          The full shape of the object returned by{" "}
          <code className="font-mono text-foreground">snapshot</code> from{" "}
          <code className="font-mono text-foreground">useIkiraro</code>.
        </p>
        <CodeBlock code={SNIPPET_RUNTIME_SNAPSHOT} label="RuntimeSnapshot" />
      </section>

      {/* FeatureVector */}
      <section className="space-y-4">
        <SectionHead id="feature-vector" label="FeatureVector" />
        <p className="text-muted-foreground text-[13px] leading-relaxed">
          Produced by the FeatureExtractor stage of the vision pipeline. Used internally by
          SurgicalMatcher for pose classification — you won't interact with this directly unless
          you're extending the vision classifier.
        </p>
        <CodeBlock code={SNIPPET_FEATURE_VECTOR} label="FeatureVector" />
      </section>

      {/* Architecture */}
      <section className="space-y-6">
        <SectionHead id="architecture" label="Architecture" />
        <p className="text-muted-foreground text-[13px] leading-relaxed">
          The SDK is a facade — it contains no logic of its own. It re-exports stable surfaces from
          three internal packages under a single versioned entry point.
        </p>

        <div className="relative pl-4 border-l-2 border-border space-y-0">
          {[
            {
              pkg: "@ikiraro/sdk",
              role: "Public facade",
              dir: "outward",
              desc: "Re-exports selected stable APIs. This is what you install. Has no implementation of its own.",
            },
            {
              pkg: "@ikiraro/runtime",
              role: "Runtime & hooks",
              dir: "inward",
              desc: "IkiraroRuntime, EventBus, 7 plugins, createIkiraro factory, useIkiraro and useHandTracking React hooks, Groq AI services.",
            },
            {
              pkg: "@ikiraro/renderer",
              role: "UI library",
              dir: "inward",
              desc: "AvatarViewer (R3F), AudioVisualizer, AslHandSvg, Button, HandOverlay. Depends on @ikiraro/engine for types.",
            },
            {
              pkg: "@ikiraro/engine",
              role: "Core — no deps",
              dir: "inward",
              desc: "Pure math, ASL pose library, vision classifier, sign planners, RendererDirector. No React, no I/O, no network. Everything else depends on this.",
            },
          ].map(({ pkg, role, desc }) => (
            <div key={pkg} className="relative pb-6">
              <div className="absolute -left-[21px] top-1 w-3 h-3 rounded-full bg-border border-2 border-background" />
              <div className="pl-4">
                <div className="flex items-center gap-2 mb-1">
                  <code className="text-foreground font-mono text-[12px] font-semibold">{pkg}</code>
                  <span className="text-muted-foreground text-[10px] uppercase tracking-[0.1em]">
                    {role}
                  </span>
                </div>
                <p className="text-muted-foreground text-[12px] leading-relaxed">{desc}</p>
              </div>
            </div>
          ))}
        </div>

        <div className="space-y-2">
          <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground">
            Design principles
          </p>
          <ul className="space-y-2 text-[12px] text-muted-foreground">
            {[
              "Local-first — the engine runs entirely in the browser. Groq is an optional enhancement, not a hard dependency.",
              "Deterministic by default — translateUnits() produces the same frame sequence for the same input every time. LLM variance is opt-in via translate().",
              "Effect-based I/O — Groq STT, Groq LLM, and camera access are wrapped in typed Effect layers for composable error handling.",
              "Plugin architecture — every capability is a plugin. The runtime is an EventBus plus a reducer. Add, remove, or override any plugin.",
              "Typed throughout — the EventRegistry covers all 34 events; SignPlan IR, FeatureVector, and CameraTrackingState are fully typed.",
            ].map((p) => (
              <li key={p} className="flex gap-2 leading-relaxed">
                <span className="text-foreground shrink-0">—</span>
                <span>{p}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>
    </div>
  );
}
