/**
 * build-letter-templates.ts
 *
 * Builds multi-template letter models for the SignAllRecognizer from the
 * sid220/asl-now-fingerspelling samples (same MediaPipe Web landmarks the app
 * sees at runtime).
 *
 * Per letter: samples are normalized (normalizeHand), flipped to canonical
 * chirality, then clustered with 2-means; each cluster's component-wise median
 * becomes a template. Multiple templates capture style variation (e.g. open vs
 * tucked thumb) that a single mean centroid blurs away.
 *
 * Usage:
 *   bun scripts/build-letter-templates.ts <aslnow-dir> --write
 * (imported by eval-recognition.ts for held-out evaluation)
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { TrainedSign } from "../src/vision/canonical-landmarks";
import { canonicalizeChirality, normalizeHand } from "../src/vision/normalize";
import type { HandLandmarks } from "../src/vision/types";

const LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
const MIN_CLUSTER = 8;

export interface LetterSamples {
  train: HandLandmarks[];
  test: HandLandmarks[];
}

/** Deterministic per-letter half split (sorted filenames, alternating). */
export function loadSplit(dir: string): Map<string, LetterSamples> {
  const out = new Map<string, LetterSamples>();
  for (const letter of LETTERS) {
    let files: string[];
    try {
      files = readdirSync(join(dir, letter))
        .filter((f) => f.endsWith(".json"))
        .sort();
    } catch {
      continue;
    }
    const train: HandLandmarks[] = [];
    const test: HandLandmarks[] = [];
    files.forEach((f, i) => {
      try {
        const lm = JSON.parse(readFileSync(join(dir, letter, f), "utf8")) as HandLandmarks;
        if (Array.isArray(lm) && lm.length === 21) {
          (i % 2 === 0 ? train : test).push(lm);
        }
      } catch {
        /* skip corrupt sample */
      }
    });
    out.set(letter, { train, test });
  }
  return out;
}

type Vec = number[]; // 63-dim flattened hand

const flatten = (lm: HandLandmarks): Vec => lm.flatMap((p) => [p.x, p.y, p.z]);
const unflatten = (v: Vec): HandLandmarks =>
  Array.from({ length: 21 }, (_, i) => ({ x: v[i * 3]!, y: v[i * 3 + 1]!, z: v[i * 3 + 2]! }));

const dist2 = (a: Vec, b: Vec) => {
  let s = 0;
  for (let i = 0; i < a.length; i++) s += (a[i]! - b[i]!) ** 2;
  return s;
};

function componentMedian(vs: Vec[]): Vec {
  const out: Vec = [];
  for (let i = 0; i < vs[0]?.length; i++) {
    const col = vs.map((v) => v[i]!).sort((a, b) => a - b);
    out.push(col[Math.floor(col.length / 2)]!);
  }
  return out;
}

/** 2-means with farthest-pair init; falls back to one cluster when degenerate. */
function cluster2(vs: Vec[]): Vec[][] {
  if (vs.length < MIN_CLUSTER * 2) return [vs];
  let a = vs[0]!;
  let b = a;
  let best = -1;
  for (const v of vs) {
    const d = dist2(a, v);
    if (d > best) {
      best = d;
      b = v;
    }
  }
  best = -1;
  for (const v of vs) {
    const d = dist2(b, v);
    if (d > best) {
      best = d;
      a = v;
    }
  }
  let ca = a;
  let cb = b;
  let groups: Vec[][] = [];
  for (let iter = 0; iter < 15; iter++) {
    const ga: Vec[] = [];
    const gb: Vec[] = [];
    for (const v of vs) (dist2(v, ca) <= dist2(v, cb) ? ga : gb).push(v);
    if (ga.length < MIN_CLUSTER || gb.length < MIN_CLUSTER) return [vs];
    ca = componentMedian(ga);
    cb = componentMedian(gb);
    groups = [ga, gb];
  }
  return groups;
}

export function buildTemplates(split: Map<string, LetterSamples>): TrainedSign[] {
  const out: TrainedSign[] = [];
  for (const [letter, { train }] of split) {
    const vecs = train.map((lm) => flatten(canonicalizeChirality(normalizeHand(lm))));
    if (vecs.length < 4) continue;
    for (const group of cluster2(vecs)) {
      out.push({ name: letter, landmarks: unflatten(componentMedian(group)) });
    }
  }
  return out;
}

function emit(templates: TrainedSign[]): string {
  const fmt = (n: number) => Number(n.toFixed(4));
  const entries = templates.map((t) => {
    const pts = t.landmarks.map((p) => `{x:${fmt(p.x)},y:${fmt(p.y)},z:${fmt(p.z)}}`).join(",");
    return `  { name: "${t.name}", landmarks: [${pts}] }`;
  });
  return `import type { TrainedSign } from "./canonical-landmarks";

/**
 * Multi-template letter models for fingerspelling recognition.
 * Built from sid220/asl-now-fingerspelling (HuggingFace, MIT): per letter,
 * samples are normalized + chirality-canonicalized, 2-means clustered, and
 * each cluster's component-wise median becomes a template.
 * Generated by: bun scripts/build-letter-templates.ts
 */
export const LETTER_TEMPLATES: TrainedSign[] = [
${entries.join(",\n")}
];
`;
}

if (process.argv[1]?.endsWith("build-letter-templates.ts")) {
  const dir = process.argv[2];
  if (!dir) {
    console.error("Usage: bun build-letter-templates.ts <aslnow-dir> [--write]");
    process.exit(1);
  }
  // Shipped templates use every sample; the eval split is only for honest
  // held-out accuracy numbers.
  const split = loadSplit(dir);
  for (const s of split.values()) {
    s.train = [...s.train, ...s.test];
  }
  const templates = buildTemplates(split);
  const byLetter = new Map<string, number>();
  for (const t of templates) byLetter.set(t.name, (byLetter.get(t.name) ?? 0) + 1);
  console.log(
    `${templates.length} templates across ${byLetter.size} letters ` +
      `(${[...byLetter.entries()].filter(([, n]) => n > 1).length} letters got 2 clusters)`,
  );
  if (process.argv.includes("--write")) {
    const outPath = join(import.meta.dir, "../src/vision/letter-templates.ts");
    writeFileSync(outPath, emit(templates), "utf8");
    console.log(`wrote ${outPath}`);
  }
}
